"""empty message

Revision ID: 6769b00973cc
Revises: 
Create Date: 2018-11-23 21:25:01.104111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6769b00973cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.add_column('topic', sa.Column('node_id', sa.Integer(), nullable=True))
    op.drop_column('topic', 'topic_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('topic_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('topic', 'node_id')
    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
